api/urls.py
from django.urls import path , include
from rest_framework.routers import DefaultRouter
from .views import JuegoViewSet, JuegoAdminViewSet

from . import views
from rest_framework_simplejwt.views import(
    TokenObtainPairView,
    TokenRefreshView
)

from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView
)

router = DefaultRouter()
router.register(r'juegos',JuegoViewSet, basename='juegos'),
router.register(r'admin/juegos',JuegoAdminViewSet, basename='admin-juegos'),
urlpatterns = router.urls

urlpatterns = [
    path('', include(router.urls)),
    
    
    # jwt
    path("token/",TokenObtainPairView.as_view(),name="token_obtain_pain"),
    path("token/refresh",TokenRefreshView.as_view(),name="token_refresh"),
    # swagger
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path(
        'api/docs/',
        SpectacularSwaggerView.as_view(url_name='schema'),
        name='swagger-ui',
    ),
]

carrito/urls.py
from django.urls import path
from .import views

app_name='carrito'

urlpatterns=[
    path('',views.ver_carrito,name='ver_carrito'),
    path('agregar/<int:juego_id>',views.agregar_al_carrito,name='agregar'),
    path('eliminar/<int:juego_id>',views.eliminar_del_carrito,name='eliminar'),
    path('limpiar',views.limpiar_carrito,name='limpiar'),
]

catalogo/urls.py
from django.urls import path
from . import views



app_name='catalogo'

urlpatterns=[
    
    path('',views.lista_juegos, name='lista_juegos'),
    path('juego/<int:pk>/', views.detalle_juego, name='detalle_juego'),
]

tienda_videojuegos/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('home.urls')),
    path('catalogo/', include(('catalogo.urls', 'catalogo'), namespace='catalogo')
),
    
    # path('catalogo/',include('catalogo.urls')),
    path('buscador/',include('buscador.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('carrito/',include('carrito.urls')),
    path('noticias/',include('noticias.urls')),
    # agregados fuera de la tienda

    # conectar la api al proyecto
    path('api/', include('api.urls')),
    # portafolio personal
    path('portfolio/', include('portfolio.urls')),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalogo/models.py
from django.db import models

# Create your models here.
# class Juego(models.Model):
#     nombre=models.CharField(max_length=100)
#     precio=models.DecimalField(max_digits=6,decimal_places=2)
#     plataforma=models.CharField(max_length=200)
#     imagen=models.CharField(max_length=200,default="default.jpg")
#     def __str__(self):
#         return self.nombre

class Juego(models.Model):
    nombre = models.CharField(max_length=100)
    precio = models.DecimalField(max_digits=6, decimal_places=2)
    plataforma = models.CharField(max_length=200)

    imagen = models.ImageField(
        upload_to='juegos/',
        blank=True,
        null=True
    )

    def __str__(self):
        return self.nombre

catalogo/views.py
from django.shortcuts import render,get_object_or_404
from django.core.paginator import Paginator
from catalogo.models import Juego

# Create your views here.
def lista_juegos(request):
    juegos=Juego.objects.all().order_by('id')#mantenemos un orden consistente
    paginator= Paginator(juegos,6)
    # obtemos el numero de pagina desde la url(pagina=2)
    page_number=request.GET.get('page')
    # obtenemos los objetos de esa pagina
    page_obj= paginator.get_page(page_number)
    
    # pasamos la plantilla como lista_juegos
    contexto_catalogo_juegos={'lista_juegos':page_obj}
    return render(request,'catalogo/lista_juegos.html',contexto_catalogo_juegos)

def detalle_juego(request,pk):
    # obtenemos el juego en concreto o mostramos un error 404 si no existe
    juego= get_object_or_404(Juego,pk=pk)
    # creamos el contexto que oasaremos a la plantilla
    contexto={'juego':juego}
    # renderizamos la plantilla detalle
    return render(request,'catalogo/detalle_juego.html',contexto)

catalogo/templates/catalogo/detalle_juego.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ juego.nombre }}{% endblock %}

{% block content %}
<div class="container py-5">
  <div class="row g-5 align-items-start">

    <!-- Imagen -->
    <div class="col-12 col-md-4">
      <div class="card shadow-sm border-0 overflow-hidden">
        {% if juego.imagen %}
          <img
            src="{{ juego.imagen.url }}"
            class="detalle-img img-fluid rounded-3"
            alt="Imagen del juego {{ juego.nombre }}"
          >
        {% else %}
          <img
            src="{% static 'img/default.jpg' %}"
            class="detalle-img img-fluid rounded-3"
            alt="Sin imagen"
          >
        {% endif %}
      </div>
    </div>

    <!-- Información -->
    <div class="col-12 col-md-8 text-start">
      <h1 class="display-5 fw-bold mb-3 text-body">{{ juego.nombre }}</h1>

      <div class="mb-4">
        <h2 class="text-success fw-bold">{{ juego.precio }} $</h2>
        <small class="text-body-secondary">Impuestos incluidos</small>
      </div>

      <p class="text-body mb-4">
        <strong>Disponible en:</strong> {{ juego.plataforma }}
      </p>

      <div class="d-flex flex-column flex-sm-row gap-3 mb-5">
        <a href="{% url 'carrito:agregar' juego.id %}" class="btn btn-success">
          <i class="fas fa-shopping-cart me-2"></i> Añadir carrito
        </a>

        <button class="btn btn-outline-danger">
          <i class="fas fa-heart me-2"></i> Agregar a favorito
        </button>

        <a href="{% url 'catalogo:lista_juegos' %}" class="btn btn-secondary">
          <i class="fas fa-arrow-left me-2"></i> Volver al catálogo
        </a>
      </div>

      <div class="mb-5">
        <h5 class="fw-semibold mb-3 text-body">Detalle del producto</h5>
        <p><strong>Plataforma:</strong> {{ juego.plataforma }}</p>
      </div>

    </div>
  </div>
</div>
{% endblock %}

catalogo/templates/catalogo/lista_juegos.html
{% extends "base.html" %}
{% load static %}

{% block title %}Listado de Juegos{% endblock %}

{% block content %}
<br>
<h2 class="text-body">Lista de juegos</h2>
<br>

<div class="row row-cols-1 row-cols-md-3 g-4">
  {% for juego in lista_juegos %}
    <div class="col">
      <a href="{% url 'catalogo:detalle_juego' juego.pk %}"
         class="text-decoration-none text-dark">

        <div class="card h-100 shadow-sm border-0 juego-card">
          
          {% if juego.imagen %}
          <img src="{{ juego.imagen.url }}" class="card-img-top img-juego" alt="{{ juego.nombre }}">
          {% else %}
          <img src="{% static 'img/default.jpg' %}" class="card-img-top img-juego" alt="Sin imagen">
          {% endif %}


          <div class="card-body d-flex flex-column text-center">
            <h5 class="card-title">{{ juego.nombre }}</h5>
            <p class="card-text">Plataforma: {{ juego.plataforma }}</p>
            <p class="card-text fw-bold">Precio: {{ juego.precio }} $</p>

            <span class="btn btn-primary mt-auto">
              <i class="fas fa-info-circle"></i> Ver detalle
            </span>
          </div>
        </div>

      </a>
    </div>
  {% endfor %}
</div>

<!-- PAGINACIÓN -->
<nav class="mt-4">
  <ul class="pagination justify-content-center">

    {% if lista_juegos.has_previous %}
      <li class="page-item">
        <a class="page-link"
           href="?page={{ lista_juegos.previous_page_number }}">
          Anterior
        </a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <span class="page-link">Anterior</span>
      </li>
    {% endif %}

    {% for num in lista_juegos.paginator.page_range %}
      {% if lista_juegos.number == num %}
        <li class="page-item active">
          <span class="page-link">{{ num }}</span>
        </li>
      {% else %}
        <li class="page-item">
          <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
      {% endif %}
    {% endfor %}

    {% if lista_juegos.has_next %}
      <li class="page-item">
        <a class="page-link"
           href="?page={{ lista_juegos.next_page_number }}">
          Siguiente
        </a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <span class="page-link">Siguiente</span>
      </li>
    {% endif %}

  </ul>
</nav>

{% endblock %}